ALTER TABLE bookings ADD COLUMN IF NOT EXISTS quantity_qtl NUMERIC(8,2);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS vehicle_number VARCHAR(20);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS driver_name VARCHAR(120);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS moisture_declared BOOLEAN NOT NULL DEFAULT false;
